apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongoSecretName }}
                key: mongo-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongoSecretName }}
                key: mongo-password
          - name: MONGO_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.mongoConfigName }}
                key: mongo-url
